#!/usr/bin/env bash
# Generated by tmux-ticket-layout — re-run install.sh to regenerate from new answers.
# Usage: layout.sh <ticket-id>
# From tmux: prefix + W  |  From shell: tw <ticket-id>

set -euo pipefail

PROJECT_ROOT="{{PROJECT_ROOT}}"
WORKTREE_BASE="{{WORKTREE_BASE}}"

TICKET="${1:-}"
[[ -z "$TICKET" ]] && { echo "Usage: layout.sh <ticket-id>" >&2; exit 1; }

SESSION="$TICKET"
WIN="$TICKET"

command -v tmux >/dev/null 2>&1 || { echo "tmux not found" >&2; exit 1; }

attach_or_switch() {
  if [[ -n "${TMUX:-}" ]]; then
    tmux switch-client -t "$SESSION"
  else
    tmux attach -t "$SESSION"
  fi
}

# Re-attach if session already exists
if tmux has-session -t "$SESSION" 2>/dev/null; then
  attach_or_switch
  exit 0
fi

WORKTREE="${WORKTREE_BASE}/${TICKET}"

# Create git worktree if it doesn't exist
if [[ ! -d "$WORKTREE" ]]; then
  echo "Creating worktree '${TICKET}' at ${WORKTREE}" >&2
  mkdir -p "$WORKTREE_BASE"
  git -C "$PROJECT_ROOT" worktree add "$WORKTREE" -b "$TICKET"
fi

# ── Pane 1: left (main AI / editor pane) ──────────────────────────────────────
tmux new-session -ds "$SESSION" -n "$WIN" -c "$WORKTREE"
{{#if PANE1_SHELL_HELPERS}}
tmux send-keys -t "$SESSION:$WIN.1" "source {{PANE1_SHELL_HELPERS}}" C-m
{{/if}}
tmux send-keys -t "$SESSION:$WIN.1" "{{PANE1_CMD}}" C-m

# ── Pane 2: top-right (staged — press Enter to run) ───────────────────────────
tmux split-window -h -t "$SESSION:$WIN" -c "$WORKTREE"
{{#if PANE2_CMD}}
tmux send-keys -t "$SESSION:$WIN.2" "{{PANE2_CMD}}"
{{/if}}

{{#if PANE3_DIR}}
# ── Pane 3: middle-right ──────────────────────────────────────────────────────
tmux split-window -v -t "$SESSION:$WIN" -c "{{PANE3_DIR}}"
tmux send-keys -t "$SESSION:$WIN.3" "{{PANE3_CMD}}"
{{/if}}

{{#if PANE4_DIR}}
# ── Pane 4: bottom-right ─────────────────────────────────────────────────────
tmux split-window -v -t "$SESSION:$WIN" -c "{{PANE4_DIR}}"
tmux send-keys -t "$SESSION:$WIN.4" "{{PANE4_CMD}}"
{{/if}}

tmux select-layout -t "$SESSION:$WIN" main-vertical
tmux select-pane -t "$SESSION:$WIN.1"

attach_or_switch
