#!/usr/bin/env bash
# shellcheck shell=bash
# Idempotent file-writing helpers.

INSTALL_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

_backup() {
  local target="$1"
  [[ -e "$target" ]] || return 0
  local stamp
  stamp="$(date +%Y%m%d-%H%M%S)"
  local backup="${target}.backup.${stamp}"
  cp -a "$target" "$backup"
  log::info "Backed up $(basename "$target") → $backup"
}

# Render layout.template.sh → ~/.config/tmux/layout.sh
# Replaces {{TOKEN}} placeholders and strips {{#if VAR}}...{{/if}} blocks for empty vars.
write::layout_sh() {
  local template="${INSTALL_ROOT}/layout.template.sh"
  local dest="${HOME}/.config/tmux/layout.sh"

  mkdir -p "${HOME}/.config/tmux"
  _backup "$dest"

  awk -v PROJECT_ROOT="${TMUX_LAYOUT_PROJECT_ROOT}" \
      -v WORKTREE_BASE="${TMUX_LAYOUT_WORKTREE_BASE}" \
      -v PANE1_CMD="${TMUX_LAYOUT_PANE1_CMD}" \
      -v PANE1_SHELL_HELPERS="${TMUX_LAYOUT_SHELL_HELPERS:-}" \
      -v PANE2_CMD="${TMUX_LAYOUT_PANE2_CMD:-}" \
      -v PANE3_DIR="${TMUX_LAYOUT_PANE3_DIR:-}" \
      -v PANE3_CMD="${TMUX_LAYOUT_PANE3_CMD:-}" \
      -v PANE4_DIR="${TMUX_LAYOUT_PANE4_DIR:-}" \
      -v PANE4_CMD="${TMUX_LAYOUT_PANE4_CMD:-}" \
  '
  # Track whether we are inside a {{#if VAR}}...{{/if}} block that is false.
  BEGIN { skip = 0; skip_depth = 0 }

  # Handle {{#if VAR}} — extract varname without capture groups (POSIX awk compat)
  /\{\{#if [A-Z0-9_]+\}\}/ {
    line = $0
    sub(/.*\{\{#if /, "", line)
    sub(/\}\}.*/, "", line)
    varname = line
    val = ""
    if      (varname == "PANE1_SHELL_HELPERS") val = PANE1_SHELL_HELPERS
    else if (varname == "PANE2_CMD")           val = PANE2_CMD
    else if (varname == "PANE3_DIR")           val = PANE3_DIR
    else if (varname == "PANE4_DIR")           val = PANE4_DIR
    if (val == "") { skip++; skip_depth++ }
    next
  }

  /\{\{\/if\}\}/ {
    if (skip_depth > 0) { skip_depth--; if (skip_depth == 0) skip = 0 }
    next
  }

  skip > 0 { next }

  {
    gsub(/\{\{PROJECT_ROOT\}\}/, PROJECT_ROOT)
    gsub(/\{\{WORKTREE_BASE\}\}/, WORKTREE_BASE)
    gsub(/\{\{PANE1_CMD\}\}/, PANE1_CMD)
    gsub(/\{\{PANE1_SHELL_HELPERS\}\}/, PANE1_SHELL_HELPERS)
    gsub(/\{\{PANE2_CMD\}\}/, PANE2_CMD)
    gsub(/\{\{PANE3_DIR\}\}/, PANE3_DIR)
    gsub(/\{\{PANE3_CMD\}\}/, PANE3_CMD)
    gsub(/\{\{PANE4_DIR\}\}/, PANE4_DIR)
    gsub(/\{\{PANE4_CMD\}\}/, PANE4_CMD)
    print
  }
  ' "$template" > "$dest"

  chmod +x "$dest"
  log::ok "layout.sh written to $dest"
}

# Copy tmux config files to ~/.config/tmux/
write::tmux_files() {
  mkdir -p "${HOME}/.config/tmux"
  cp "${INSTALL_ROOT}/tmux/launch-layout.sh" "${HOME}/.config/tmux/launch-layout.sh"
  cp "${INSTALL_ROOT}/tmux/work-layout.sh"   "${HOME}/.config/tmux/work-layout.sh"
  chmod +x "${HOME}/.config/tmux/launch-layout.sh" "${HOME}/.config/tmux/work-layout.sh"
  log::ok "launch-layout.sh and work-layout.sh installed to ~/.config/tmux/"
}

write::tmux_conf_full() {
  local src="${INSTALL_ROOT}/tmux/tmux.conf"
  local conf_dest="${HOME}/.config/tmux/tmux.conf"
  local stub_dest="${HOME}/.tmux.conf"

  _backup "$conf_dest"
  _backup "$stub_dest"

  cp "$src" "$conf_dest"
  printf '# Generated by tmux-ticket-layout\nsource-file ~/.config/tmux/tmux.conf\n' > "$stub_dest"

  log::ok "tmux.conf written to $conf_dest"
  log::ok "~/.tmux.conf stub written"
}

write::tmux_conf_keybind_only() {
  local target="${HOME}/.tmux.conf"
  local bind_line='bind-key W command-prompt -p "Ticket:" "run-shell '"'"'bash #{HOME}/.config/tmux/launch-layout.sh %%'"'"'"'

  if grep -q "launch-layout.sh" "$target" 2>/dev/null; then
    log::skip "prefix+W bind already present in ~/.tmux.conf"
    return
  fi

  {
    echo ""
    echo "# tmux-ticket-layout: ticket-aware session launcher"
    echo "$bind_line"
  } >> "$target"
  log::ok "prefix+W keybind appended to ~/.tmux.conf"
}

write::tw_alias() {
  local shell_rc
  case "${SHELL:-}" in
    */zsh)  shell_rc="${HOME}/.zshrc" ;;
    */bash) shell_rc="${HOME}/.bashrc" ;;
    *)      shell_rc="${HOME}/.zshrc" ;;
  esac

  local alias_line="alias tw='bash \"\${HOME}/.config/tmux/launch-layout.sh\"'"

  if grep -q "launch-layout.sh" "$shell_rc" 2>/dev/null; then
    log::skip "tw alias already present in $shell_rc"
    return
  fi

  {
    echo ""
    echo "# tmux-ticket-layout: launch a ticket session"
    echo "$alias_line"
  } >> "$shell_rc"
  log::ok "tw alias added to $shell_rc"
}
