#!/usr/bin/env bash
# Dispatcher: prefer machine-local layout.sh (generated by install.sh) over work-layout.sh.
# Usage: launch-layout.sh [session-name]

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [[ -f "$SCRIPT_DIR/layout.sh" ]]; then
  exec bash "$SCRIPT_DIR/layout.sh" "$@"
else
  exec bash "$SCRIPT_DIR/work-layout.sh" "$@"
fi
